-- Migration: 20260228_hyrox_staging_6_tables
-- Description: Create Hyrox staging schema with 6 tables (refined design)
-- Tables: hyrox_workouts_staging, hyrox_workout_lines_staging, hyrox_mini_circuits_staging,
--          hyrox_time_segments_staging, hyrox_ladder_rungs_staging, hyrox_workout_tags_staging

-- ==== UP ====
BEGIN;

-- Create ENUM types
CREATE TYPE hyrox_workout_type AS ENUM (
  'amrap',
  'emom',
  'for_time',
  'rounds_for_time',
  'for_load',
  'buy_in',
  'cash_out',
  'time_cap',
  'ladder',
  'mini_circuit',
  'explicit_time_guidance',
  'unknown'
);

CREATE TYPE hyrox_workout_goal AS ENUM (
  'max_rounds_reps',
  'finish_quickly',
  'complete_rounds',
  'max_load',
  'pace_work',
  'endurance',
  'strength',
  'mixed',
  'unknown'
);

CREATE TYPE hyrox_status AS ENUM (
  'pending_review',
  'reviewed',
  'approved',
  'rejected'
);

-- Table 1: hyrox_workouts_staging (core workout metadata)
CREATE TABLE hyrox_workouts_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  wod_id VARCHAR(100),
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  badge TEXT,
  workout_type hyrox_workout_type NOT NULL DEFAULT 'unknown',
  workout_goal hyrox_workout_goal DEFAULT 'unknown',
  time_specification VARCHAR(100),
  total_time_minutes INTEGER,
  time_cap_minutes INTEGER,
  has_buy_in BOOLEAN NOT NULL DEFAULT false,
  has_cash_out BOOLEAN NOT NULL DEFAULT false,
  is_complex BOOLEAN NOT NULL DEFAULT false,
  full_description TEXT,
  scraped_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  source_page VARCHAR(100),
  status hyrox_status NOT NULL DEFAULT 'pending_review',
  notes TEXT
);

-- Indexes for hyrox_workouts_staging
CREATE INDEX idx_hyrox_workouts_staging_name ON hyrox_workouts_staging(name);
CREATE INDEX idx_hyrox_workouts_staging_type ON hyrox_workouts_staging(workout_type);
CREATE INDEX idx_hyrox_workouts_staging_status ON hyrox_workouts_staging(status);
CREATE INDEX idx_hyrox_workouts_staging_scraped_at ON hyrox_workouts_staging(scraped_at);

-- Table 2: hyrox_workout_lines_staging (movement grain table)
CREATE TABLE hyrox_workout_lines_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL,
  line_text TEXT NOT NULL,
  is_rest BOOLEAN NOT NULL DEFAULT false,
  is_buy_in BOOLEAN NOT NULL DEFAULT false,
  is_cash_out BOOLEAN NOT NULL DEFAULT false,
  movement_name VARCHAR(200),
  reps INTEGER,
  distance_meters NUMERIC(10,2),
  duration_seconds INTEGER,
  weight_male NUMERIC(10,2),
  weight_female NUMERIC(10,2),
  calories INTEGER,
  is_max_effort BOOLEAN NOT NULL DEFAULT false,
  notes TEXT,
  mini_circuit_id INTEGER,
  time_segment_id INTEGER,
  ladder_rung_id INTEGER,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for hyrox_workout_lines_staging
CREATE INDEX idx_hyrox_workout_lines_staging_workout ON hyrox_workout_lines_staging(workout_id);
CREATE INDEX idx_hyrox_workout_lines_staging_movement ON hyrox_workout_lines_staging(movement_name);
CREATE INDEX idx_hyrox_workout_lines_staging_circuit ON hyrox_workout_lines_staging(mini_circuit_id);
CREATE INDEX idx_hyrox_workout_lines_staging_segment ON hyrox_workout_lines_staging(time_segment_id);
CREATE INDEX idx_hyrox_workout_lines_staging_ladder ON hyrox_workout_lines_staging(ladder_rung_id);

-- Table 3: hyrox_mini_circuits_staging (for workouts with multiple circuits)
CREATE TABLE hyrox_mini_circuits_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
  circuit_number INTEGER NOT NULL,
  circuit_type hyrox_workout_type NOT NULL,
  start_time TIME,
  end_time TIME,
  duration_minutes INTEGER,
  rest_after_minutes INTEGER,
  notes TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for hyrox_mini_circuits_staging
CREATE INDEX idx_hyrox_mini_circuits_staging_workout ON hyrox_mini_circuits_staging(workout_id);

-- Table 4: hyrox_time_segments_staging (for explicit time guidance workouts)
CREATE TABLE hyrox_time_segments_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
  segment_number INTEGER NOT NULL,
  start_time TIME,
  end_time TIME,
  duration_minutes INTEGER,
  notes TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for hyrox_time_segments_staging
CREATE INDEX idx_hyrox_time_segments_staging_workout ON hyrox_time_segments_staging(workout_id);

-- Table 5: hyrox_ladder_rungs_staging (for ladder workouts)
CREATE TABLE hyrox_ladder_rungs_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
  rung_number INTEGER NOT NULL,
  reps_per_exercise INTEGER,
  is_ascending BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for hyrox_ladder_rungs_staging
CREATE INDEX idx_hyrox_ladder_rungs_staging_workout ON hyrox_ladder_rungs_staging(workout_id);

-- Table 6: hyrox_workout_tags_staging (for workout categorization)
CREATE TABLE hyrox_workout_tags_staging (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
  tag_name VARCHAR(100) NOT NULL,
  tag_url TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for hyrox_workout_tags_staging
CREATE INDEX idx_hyrox_workout_tags_staging_workout ON hyrox_workout_tags_staging(workout_id);

-- Add foreign key constraints from lines to structure tables
ALTER TABLE hyrox_workout_lines_staging
  ADD CONSTRAINT fk_lines_mini_circuit
  FOREIGN KEY (mini_circuit_id)
  REFERENCES hyrox_mini_circuits_staging(id)
  ON DELETE SET NULL;

ALTER TABLE hyrox_workout_lines_staging
  ADD CONSTRAINT fk_lines_time_segment
  FOREIGN KEY (time_segment_id)
  REFERENCES hyrox_time_segments_staging(id)
  ON DELETE SET NULL;

ALTER TABLE hyrox_workout_lines_staging
  ADD CONSTRAINT fk_lines_ladder_rung
  FOREIGN KEY (ladder_rung_id)
  REFERENCES hyrox_ladder_rungs_staging(id)
  ON DELETE SET NULL;

COMMIT;

-- ==== DOWN ====
BEGIN;

-- Drop foreign key constraints from lines table
ALTER TABLE hyrox_workout_lines_staging DROP CONSTRAINT IF EXISTS fk_lines_ladder_rung;
ALTER TABLE hyrox_workout_lines_staging DROP CONSTRAINT IF EXISTS fk_lines_time_segment;
ALTER TABLE hyrox_workout_lines_staging DROP CONSTRAINT IF EXISTS fk_lines_mini_circuit;

-- Drop tables (in reverse order due to dependencies)
DROP TABLE IF EXISTS hyrox_workout_tags_staging CASCADE;
DROP TABLE IF EXISTS hyrox_ladder_rungs_staging CASCADE;
DROP TABLE IF EXISTS hyrox_time_segments_staging CASCADE;
DROP TABLE IF EXISTS hyrox_mini_circuits_staging CASCADE;
DROP TABLE IF EXISTS hyrox_workout_lines_staging CASCADE;
DROP TABLE IF EXISTS hyrox_workouts_staging CASCADE;

-- Drop ENUM types
DROP TYPE IF EXISTS hyrox_status CASCADE;
DROP TYPE IF EXISTS hyrox_workout_goal CASCADE;
DROP TYPE IF EXISTS hyrox_workout_type CASCADE;

COMMIT;
