-- Migration: 20260228_create_hyrox_staging_tables (UP ONLY)
-- Description: Create staging tables for Hyrox workout data scraped from wodwell.com
-- Author: System

BEGIN;

-- =====================================================
-- ENUM TYPES FOR HYROX WORKOUTS
-- =====================================================

-- Enum: hyrox_workout_type
CREATE TYPE hyrox_workout_type AS ENUM (
    'amrap', 'emom', 'for_time', 'rounds_for_time',
    'for_load', 'buy_in', 'cash_out', 'time_cap',
    'ladder', 'mini_circuit', 'explicit_time_guidance', 'unknown'
);

-- Enum: hyrox_workout_goal
CREATE TYPE hyrox_workout_goal AS ENUM (
    'finish_quickly', 'max_rounds_reps', 'pace_work',
    'max_load', 'complete_rounds', 'endurance',
    'strength', 'mixed', 'unknown'
);

-- Enum: hyrox_status
CREATE TYPE hyrox_status AS ENUM (
    'pending_review', 'reviewed', 'approved', 'rejected'
);

-- =====================================================
-- STAGING TABLES FOR HYROX WORKOUTS
-- =====================================================

-- Main staging table for Hyrox workouts
CREATE TABLE hyrox_workouts_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wod_id INTEGER,
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    badge TEXT,
    workout_type hyrox_workout_type NOT NULL DEFAULT 'unknown',
    workout_goal hyrox_workout_goal DEFAULT 'unknown',
    time_specification VARCHAR(100),
    total_time_minutes INTEGER,
    time_cap_minutes INTEGER,
    has_buy_in BOOLEAN DEFAULT false,
    has_cash_out BOOLEAN DEFAULT false,
    is_complex BOOLEAN DEFAULT false,
    background_image TEXT,
    favorites_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    full_description TEXT,
    scraped_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    source_page TEXT,
    status hyrox_status DEFAULT 'pending_review',
    validation_errors JSONB,
    notes TEXT
);

-- Table for workout description lines (parsed from multi-line descriptions)
CREATE TABLE hyrox_workout_lines_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    line_text TEXT NOT NULL,
    is_rest BOOLEAN DEFAULT false,
    is_buy_in BOOLEAN DEFAULT false,
    is_cash_out BOOLEAN DEFAULT false,
    movement_name VARCHAR(200),
    metric_type VARCHAR(50),
    reps INTEGER,
    distance_meters DOUBLE PRECISION,
    duration_seconds INTEGER,
    calories INTEGER,
    weight_text VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_lines_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE
);

-- Table for workout tags
CREATE TABLE hyrox_workout_tags_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    tag_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_tags_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE
);

-- Table for parsed movements (from description lines)
CREATE TABLE hyrox_workout_movements_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    line_id INTEGER,
    movement_name VARCHAR(200) NOT NULL,
    movement_type VARCHAR(50),
    reps INTEGER,
    distance_meters DOUBLE PRECISION,
    duration_seconds INTEGER,
    calories INTEGER,
    weight_male DOUBLE PRECISION,
    weight_female DOUBLE PRECISION,
    is_max_effort BOOLEAN DEFAULT false,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_movements_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
    CONSTRAINT fk_hyrox_movements_line FOREIGN KEY (line_id) 
        REFERENCES hyrox_workout_lines_staging(id) ON DELETE SET NULL
);

-- Table for mini circuits (if workout has multiple circuits)
CREATE TABLE hyrox_mini_circuits_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    circuit_number INTEGER NOT NULL,
    circuit_type hyrox_workout_type NOT NULL,
    time_specification VARCHAR(100),
    rest_after_seconds INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_mini_circuits_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE
);

-- Table for structured time segments (for explicit time guidance workouts)
CREATE TABLE hyrox_time_segments_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    segment_number INTEGER NOT NULL,
    start_time VARCHAR(50),
    end_time VARCHAR(50),
    duration_minutes INTEGER,
    movements JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_time_segments_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE
);

-- Table for ladder structure
CREATE TABLE hyrox_ladder_rungs_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    rung_number INTEGER NOT NULL,
    reps_per_exercise INTEGER,
    is_ascending BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_hyrox_ladder_rungs_workout FOREIGN KEY (workout_id) 
        REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE
);

-- Table for scraping metadata/logs
CREATE TABLE hyrox_scraping_log_staging (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scrape_session_id VARCHAR(100) NOT NULL,
    started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    total_workouts_found INTEGER DEFAULT 0,
    workouts_scraped INTEGER DEFAULT 0,
    workouts_saved INTEGER DEFAULT 0,
    errors_count INTEGER DEFAULT 0,
    has_errors BOOLEAN DEFAULT false,
    error_summary TEXT,
    user_agent TEXT,
    notes TEXT
);

-- Create indexes for better query performance
CREATE INDEX idx_hyrox_workouts_staging_name ON hyrox_workouts_staging(name);
CREATE INDEX idx_hyrox_workouts_staging_type ON hyrox_workouts_staging(workout_type);
CREATE INDEX idx_hyrox_workouts_staging_status ON hyrox_workouts_staging(status);
CREATE INDEX idx_hyrox_workouts_staging_scraped_at ON hyrox_workouts_staging(scraped_at);
CREATE INDEX idx_hyrox_workout_lines_staging_workout ON hyrox_workout_lines_staging(workout_id);
CREATE INDEX idx_hyrox_workout_tags_staging_workout ON hyrox_workout_tags_staging(workout_id);
CREATE INDEX idx_hyrox_workout_movements_staging_workout ON hyrox_workout_movements_staging(workout_id);
CREATE INDEX idx_hyrox_mini_circuits_staging_workout ON hyrox_mini_circuits_staging(workout_id);
CREATE INDEX idx_hyrox_time_segments_staging_workout ON hyrox_time_segments_staging(workout_id);
CREATE INDEX idx_hyrox_ladder_rungs_staging_workout ON hyrox_ladder_rungs_staging(workout_id);
CREATE INDEX idx_hyrox_scraping_log_staging_session ON hyrox_scraping_log_staging(scrape_session_id);

COMMIT;
