-- Migration: 20260301_create_hyrox_production_tables
-- Description: Create production tables for Hyrox workout data (mirroring staging schema)
-- Author: System

-- ==== UP ====
BEGIN;

-- =====================================================
-- PRODUCTION TABLES FOR HYROX WORKOUTS
-- =====================================================
-- Note: Enum types (hyrox_workout_type, hyrox_workout_goal, hyrox_status)
-- are assumed to already exist from staging table migration

-- Main production table for Hyrox workouts
CREATE TABLE IF NOT EXISTS hyrox_workouts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wod_id VARCHAR(100),
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    badge TEXT,
    workout_type hyrox_workout_type NOT NULL DEFAULT 'unknown',
    workout_goal hyrox_workout_goal DEFAULT 'unknown',
    time_specification VARCHAR(100),
    total_time_minutes INTEGER,
    time_cap_minutes INTEGER,
    has_buy_in BOOLEAN NOT NULL DEFAULT false,
    has_cash_out BOOLEAN NOT NULL DEFAULT false,
    is_complex BOOLEAN NOT NULL DEFAULT false,
    full_description TEXT,
    scraped_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    source_page VARCHAR(100),
    status hyrox_status NOT NULL DEFAULT 'pending_review',
    notes TEXT
);

-- Table for workout description lines (parsed from multi-line descriptions)
CREATE TABLE IF NOT EXISTS hyrox_workout_lines (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    line_text TEXT NOT NULL,
    is_rest BOOLEAN NOT NULL DEFAULT false,
    is_buy_in BOOLEAN NOT NULL DEFAULT false,
    is_cash_out BOOLEAN NOT NULL DEFAULT false,
    movement_name VARCHAR(200),
    reps INTEGER,
    distance_meters NUMERIC(10,2),
    duration_seconds INTEGER,
    weight_male NUMERIC(10,2),
    weight_female NUMERIC(10,2),
    calories INTEGER,
    is_max_effort BOOLEAN NOT NULL DEFAULT false,
    notes TEXT,
    mini_circuit_id INTEGER,
    time_segment_id INTEGER,
    ladder_rung_id INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    movement_id INTEGER,
    CONSTRAINT fk_hyrox_lines_workout FOREIGN KEY (workout_id)
        REFERENCES hyrox_workouts(id) ON DELETE CASCADE,
    CONSTRAINT fk_hyrox_lines_movement FOREIGN KEY (movement_id)
        REFERENCES movements(id) ON DELETE SET NULL
);

-- Table for workout tags
CREATE TABLE IF NOT EXISTS hyrox_workout_tags (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_id INTEGER NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    tag_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_hyrox_tags_workout FOREIGN KEY (workout_id)
        REFERENCES hyrox_workouts(id) ON DELETE CASCADE
);

-- Table for scraping metadata/logs
CREATE TABLE IF NOT EXISTS hyrox_scraping_log (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scrape_session_id VARCHAR(100) NOT NULL,
    started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    total_workouts_found INTEGER DEFAULT 0,
    workouts_scraped INTEGER DEFAULT 0,
    workouts_saved INTEGER DEFAULT 0,
    errors_count INTEGER DEFAULT 0,
    has_errors BOOLEAN DEFAULT false,
    error_summary TEXT,
    user_agent TEXT,
    notes TEXT
);

-- =====================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =====================================================

-- hyrox_workouts indexes
CREATE INDEX IF NOT EXISTS idx_hyrox_workouts_name ON hyrox_workouts(name);
CREATE INDEX IF NOT EXISTS idx_hyrox_workouts_type ON hyrox_workouts(workout_type);
CREATE INDEX IF NOT EXISTS idx_hyrox_workouts_status ON hyrox_workouts(status);
CREATE INDEX IF NOT EXISTS idx_hyrox_workouts_scraped_at ON hyrox_workouts(scraped_at);

-- hyrox_workout_lines indexes
CREATE INDEX IF NOT EXISTS idx_hyrox_workout_lines_workout ON hyrox_workout_lines(workout_id);
CREATE INDEX IF NOT EXISTS idx_hyrox_lines_movement_name ON hyrox_workout_lines(movement_name);
CREATE INDEX IF NOT EXISTS idx_hyrox_lines_movement_id ON hyrox_workout_lines(movement_id);
CREATE INDEX IF NOT EXISTS idx_hyrox_lines_circuit ON hyrox_workout_lines(mini_circuit_id);
CREATE INDEX IF NOT EXISTS idx_hyrox_lines_segment ON hyrox_workout_lines(time_segment_id);
CREATE INDEX IF NOT EXISTS idx_hyrox_lines_ladder ON hyrox_workout_lines(ladder_rung_id);

-- hyrox_workout_tags indexes
CREATE INDEX IF NOT EXISTS idx_hyrox_workout_tags_workout ON hyrox_workout_tags(workout_id);

-- hyrox_scraping_log indexes
CREATE INDEX IF NOT EXISTS idx_hyrox_scraping_log_session ON hyrox_scraping_log(scrape_session_id);

COMMIT;

-- ==== DOWN ====
BEGIN;

-- Drop indexes (production tables)
DROP INDEX IF EXISTS idx_hyrox_scraping_log_session;
DROP INDEX IF EXISTS idx_hyrox_workout_tags_workout;
DROP INDEX IF EXISTS idx_hyrox_lines_ladder;
DROP INDEX IF EXISTS idx_hyrox_lines_segment;
DROP INDEX IF EXISTS idx_hyrox_lines_circuit;
DROP INDEX IF EXISTS idx_hyrox_lines_movement_id;
DROP INDEX IF EXISTS idx_hyrox_lines_movement_name;
DROP INDEX IF EXISTS idx_hyrox_workout_lines_workout;
DROP INDEX IF EXISTS idx_hyrox_workouts_scraped_at;
DROP INDEX IF EXISTS idx_hyrox_workouts_status;
DROP INDEX IF EXISTS idx_hyrox_workouts_type;
DROP INDEX IF EXISTS idx_hyrox_workouts_name;

-- Drop production tables (in correct dependency order)
DROP TABLE IF EXISTS hyrox_scraping_log CASCADE;
DROP TABLE IF EXISTS hyrox_workout_tags CASCADE;
DROP TABLE IF EXISTS hyrox_workout_lines CASCADE;
DROP TABLE IF EXISTS hyrox_workouts CASCADE;

COMMIT;
