-- Migration File: Current Database Schema (2026-02-27)
-- This file represents the current state of the database.
-- When making changes, replace this entire file with the new schema.
-- History of changes can be tracked via the migration_version table.

-- =====================================================
-- ENUM TYPES
-- =====================================================

-- Enum: goaltype
CREATE TYPE goaltype AS ENUM (
    'strength', 'hypertrophy', 'endurance', 'power', 'flexibility', 'fat_loss'
);

-- Enum: splittemplate
CREATE TYPE splittemplate AS ENUM (
    'full_body', 'upper_lower', 'push_pull', 'body_part_split', 'custom'
);

-- Enum: progressionstyle
CREATE TYPE progressionstyle AS ENUM (
    'linear', 'wave', 'undulating', 'custom'
);

-- Enum: visibility
CREATE TYPE visibility AS ENUM (
    'private', 'friends', 'public'
);

-- Enum: personaaggression
CREATE TYPE personaaggression AS ENUM (
    'conservative', 'moderate', 'aggressive'
);

-- Enum: personatone
CREATE TYPE personatone AS ENUM (
    'encouraging', 'neutral', 'tough'
);

-- Enum: primarymuscle
CREATE TYPE primarymuscle AS ENUM (
    'chest', 'back', 'shoulders', 'biceps', 'triceps', 'forearms',
    'abs', 'obliques', 'lower_back', 'glutes', 'quads', 'hamstrings',
    'calves', 'traps', 'lats', 'neck'
);

-- Enum: primaryregion
CREATE TYPE primaryregion AS ENUM (
    'upper_body', 'lower_body', 'full_body', 'core', 'arms', 'legs'
);

-- Enum: metrictype
CREATE TYPE metrictype AS ENUM (
    'reps', 'time', 'distance', 'calories', 'weight'
);

-- Enum: spinalcompression
CREATE TYPE spinalcompression AS ENUM (
    'none', 'low', 'medium', 'high'
);

-- Enum: disciplinetype_new3
CREATE TYPE disciplinetype_new3 AS ENUM (
    'strength', 'endurance', 'power', 'mobility', 'mixed'
);

-- Enum: patterntype_new
CREATE TYPE patterntype_new AS ENUM (
    'linear', 'wave', 'undulating', 'random', 'custom'
);

-- Enum: muscleregion
CREATE TYPE muscleregion AS ENUM (
    'upper_body', 'lower_body', 'core', 'arms', 'legs'
);

-- =====================================================
-- TABLES
-- =====================================================

-- Table: muscles
CREATE TABLE muscles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug VARCHAR(100) NOT NULL,
    region muscleregion
);

-- Table: equipment
CREATE TABLE equipment (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

-- Table: movements
CREATE TABLE movements (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    primary_muscle primarymuscle NOT NULL,
    primary_region primaryregion NOT NULL,
    compound BOOLEAN,
    is_complex_lift BOOLEAN,
    is_unilateral BOOLEAN,
    metric_type metrictype NOT NULL,
    spinal_compression spinalcompression NOT NULL DEFAULT 'none'::spinalcompression,
    bodyweight_possible BOOLEAN DEFAULT false,
    dumbbell_possible BOOLEAN DEFAULT false,
    kettlebell_possible BOOLEAN DEFAULT false,
    barbell_possible BOOLEAN DEFAULT false,
    machine_possible BOOLEAN DEFAULT false,
    band_possible BOOLEAN DEFAULT false,
    plate_or_med_ball_possible BOOLEAN DEFAULT false,
    regression_to_move INTEGER,
    progression_to_move INTEGER,
    variation_to_move INTEGER,
    discipline disciplinetype_new3,
    pattern patterntype_new
);

-- Table: movement_muscle_map
CREATE TABLE movement_muscle_map (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    movement_id INTEGER NOT NULL,
    muscle_id INTEGER NOT NULL,
    role VARCHAR(50) NOT NULL,
    magnitude DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_movement_muscle_map_movement FOREIGN KEY (movement_id) REFERENCES movements(id) ON DELETE CASCADE,
    CONSTRAINT fk_movement_muscle_map_muscle FOREIGN KEY (muscle_id) REFERENCES muscles(id) ON DELETE CASCADE
);

-- Table: movement_equipment
CREATE TABLE movement_equipment (
    movement_id INTEGER NOT NULL,
    equipment_id INTEGER NOT NULL,
    CONSTRAINT pk_movement_equipment PRIMARY KEY (movement_id, equipment_id),
    CONSTRAINT fk_movement_equipment_movement FOREIGN KEY (movement_id) REFERENCES movements(id) ON DELETE CASCADE,
    CONSTRAINT fk_movement_equipment_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
);

-- Table: movement_coaching_cues
CREATE TABLE movement_coaching_cues (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    movement_id INTEGER NOT NULL,
    cue_text TEXT NOT NULL,
    "order" INTEGER,
    CONSTRAINT fk_movement_coaching_cues_movement FOREIGN KEY (movement_id) REFERENCES movements(id) ON DELETE CASCADE
);

-- Table: activity_definitions
CREATE TABLE activity_definitions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    discipline_id INTEGER,
    default_metric_type metrictype,
    default_equipment_tags JSON,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- Table: activity_muscle_map
CREATE TABLE activity_muscle_map (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    activity_definition_id INTEGER NOT NULL,
    muscle_id INTEGER NOT NULL,
    magnitude DOUBLE PRECISION NOT NULL,
    cns_impact DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_activity_muscle_map_activity FOREIGN KEY (activity_definition_id) REFERENCES activity_definitions(id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_muscle_map_muscle FOREIGN KEY (muscle_id) REFERENCES muscles(id) ON DELETE CASCADE
);

-- Table: circuits_melted
CREATE TABLE circuits_melted (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    circuit_id INTEGER NOT NULL,
    movement_id INTEGER,
    exercise_sequence INTEGER NOT NULL,
    movement_name VARCHAR(200) NOT NULL,
    metric_type metrictype NOT NULL,
    reps INTEGER,
    distance_meters DOUBLE PRECISION,
    duration_seconds INTEGER,
    calories INTEGER,
    rest_seconds INTEGER,
    notes TEXT,
    rx_weight_male DOUBLE PRECISION,
    rx_weight_female DOUBLE PRECISION,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION
);

-- Table: circuits_macro
CREATE TABLE circuits_macro (
    circuit_id INTEGER NOT NULL,
    total_exercises INTEGER NOT NULL,
    unique_movements INTEGER NOT NULL,
    max_rx_weight_male DOUBLE PRECISION,
    max_rx_weight_female DOUBLE PRECISION,
    required_equipment JSONB NOT NULL,
    movement_pattern_counts JSONB NOT NULL,
    metabolic_profile JSONB NOT NULL,
    default_rounds INTEGER,
    circuit_type_intensity DOUBLE PRECISION NOT NULL,
    data_completeness_score DOUBLE PRECISION NOT NULL,
    validation_errors JSONB NOT NULL,
    created_at DOUBLE PRECISION,
    updated_at DOUBLE PRECISION,
    primary_region primaryregion NOT NULL DEFAULT 'full body'::primaryregion,
    CONSTRAINT pk_circuits_macro PRIMARY KEY (circuit_id)
);

-- Table: tags
CREATE TABLE tags (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

-- =====================================================
-- MIGRATION TRACKING
-- =====================================================

-- Table: migration_version
CREATE TABLE IF NOT EXISTS migration_version (
    version VARCHAR(50) PRIMARY KEY,
    description TEXT,
    applied_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    checksum VARCHAR(64)
);

-- NOTE: The migration system uses checksums to detect changes.
-- When applying this file, the migrate.sh script will:
-- 1. Calculate the MD5 checksum of this entire file
-- 2. Check if this checksum already exists in migration_version
-- 3. Only apply if the checksum is different (new changes)
