/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding/$step'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReadinessRouteImport } from './routes/_app/readiness'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProgramIndexRouteImport } from './routes/_app/program/index'
import { Route as AppWorkoutSessionIdRouteImport } from './routes/_app/workout/$sessionId'
import { Route as AppProgramProgramIdRouteImport } from './routes/_app/program/$programId'
import { Route as AppWorkoutBuilderSessionIdRouteImport } from './routes/_app/workout/builder.$sessionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramIndexRoute = AppProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutSessionIdRoute = AppWorkoutSessionIdRouteImport.update({
  id: '/workout/$sessionId',
  path: '/workout/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramProgramIdRoute = AppProgramProgramIdRouteImport.update({
  id: '/program/$programId',
  path: '/program/$programId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutBuilderSessionIdRoute =
  AppWorkoutBuilderSessionIdRouteImport.update({
    id: '/workout/builder/$sessionId',
    path: '/workout/builder/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/readiness': typeof AppReadinessRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/program/$programId': typeof AppProgramProgramIdRoute
  '/workout/$sessionId': typeof AppWorkoutSessionIdRoute
  '/program/': typeof AppProgramIndexRoute
  '/workout/builder/$sessionId': typeof AppWorkoutBuilderSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/readiness': typeof AppReadinessRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/program/$programId': typeof AppProgramProgramIdRoute
  '/workout/$sessionId': typeof AppWorkoutSessionIdRoute
  '/program': typeof AppProgramIndexRoute
  '/workout/builder/$sessionId': typeof AppWorkoutBuilderSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/readiness': typeof AppReadinessRoute
  '/_app/settings': typeof AppSettingsRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/program/$programId': typeof AppProgramProgramIdRoute
  '/_app/workout/$sessionId': typeof AppWorkoutSessionIdRoute
  '/_app/program/': typeof AppProgramIndexRoute
  '/_app/workout/builder/$sessionId': typeof AppWorkoutBuilderSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/readiness'
    | '/settings'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/program/$programId'
    | '/workout/$sessionId'
    | '/program/'
    | '/workout/builder/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/readiness'
    | '/settings'
    | '/onboarding/$step'
    | '/onboarding'
    | '/program/$programId'
    | '/workout/$sessionId'
    | '/program'
    | '/workout/builder/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/readiness'
    | '/_app/settings'
    | '/onboarding/$step'
    | '/onboarding/'
    | '/_app/program/$programId'
    | '/_app/workout/$sessionId'
    | '/_app/program/'
    | '/_app/workout/builder/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/readiness': {
      id: '/_app/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/program/': {
      id: '/_app/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof AppProgramIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout/$sessionId': {
      id: '/_app/workout/$sessionId'
      path: '/workout/$sessionId'
      fullPath: '/workout/$sessionId'
      preLoaderRoute: typeof AppWorkoutSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/program/$programId': {
      id: '/_app/program/$programId'
      path: '/program/$programId'
      fullPath: '/program/$programId'
      preLoaderRoute: typeof AppProgramProgramIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workout/builder/$sessionId': {
      id: '/_app/workout/builder/$sessionId'
      path: '/workout/builder/$sessionId'
      fullPath: '/workout/builder/$sessionId'
      preLoaderRoute: typeof AppWorkoutBuilderSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProgramProgramIdRoute: typeof AppProgramProgramIdRoute
  AppWorkoutSessionIdRoute: typeof AppWorkoutSessionIdRoute
  AppProgramIndexRoute: typeof AppProgramIndexRoute
  AppWorkoutBuilderSessionIdRoute: typeof AppWorkoutBuilderSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProgramProgramIdRoute: AppProgramProgramIdRoute,
  AppWorkoutSessionIdRoute: AppWorkoutSessionIdRoute,
  AppProgramIndexRoute: AppProgramIndexRoute,
  AppWorkoutBuilderSessionIdRoute: AppWorkoutBuilderSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
