
import psycopg2
import os

DEFAULT_DB_HOST = "localhost"
DEFAULT_DB_PORT = "5434"
DEFAULT_DB_NAME = "Jacked-DB"
DEFAULT_DB_USER = "jacked"
DEFAULT_DB_PASS = "jackedpass"

def get_db_connection():
    return psycopg2.connect(
        host=os.environ.get("DB_HOST", DEFAULT_DB_HOST),
        port=os.environ.get("DB_PORT", DEFAULT_DB_PORT),
        database=os.environ.get("DB_NAME", DEFAULT_DB_NAME),
        user=os.environ.get("DB_USER", DEFAULT_DB_USER),
        password=os.environ.get("DB_PASS", DEFAULT_DB_PASS)
    )

def apply_migration_step_by_step():
    conn = get_db_connection()
    conn.autocommit = True
    cursor = conn.cursor()
    
    commands = [
        "DROP TABLE IF EXISTS hyrox_workout_tags_staging CASCADE",
        "DROP TABLE IF EXISTS hyrox_ladder_rungs_staging CASCADE",
        "DROP TABLE IF EXISTS hyrox_time_segments_staging CASCADE",
        "DROP TABLE IF EXISTS hyrox_mini_circuits_staging CASCADE",
        "DROP TABLE IF EXISTS hyrox_workout_lines_staging CASCADE",
        "DROP TABLE IF EXISTS hyrox_workouts_staging CASCADE",
        
        """
        DO $$ BEGIN
            CREATE TYPE hyrox_workout_type AS ENUM (
                'amrap', 'emom', 'for_time', 'rounds_for_time', 'for_load',
                'buy_in', 'cash_out', 'time_cap', 'ladder', 'mini_circuit',
                'explicit_time_guidance', 'unknown'
            );
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$
        """,
        
        """
        DO $$ BEGIN
            CREATE TYPE hyrox_workout_goal AS ENUM (
                'max_rounds_reps', 'finish_quickly', 'complete_rounds', 'max_load',
                'pace_work', 'endurance', 'strength', 'mixed', 'unknown'
            );
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$
        """,
        
        """
        DO $$ BEGIN
            CREATE TYPE hyrox_status AS ENUM (
                'pending_review', 'reviewed', 'approved', 'rejected'
            );
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$
        """,
        
        """
        CREATE TABLE hyrox_workouts_staging (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          wod_id VARCHAR(100),
          name VARCHAR(255) NOT NULL,
          url TEXT NOT NULL,
          badge TEXT,
          workout_type hyrox_workout_type NOT NULL DEFAULT 'unknown',
          workout_goal hyrox_workout_goal DEFAULT 'unknown',
          time_specification VARCHAR(100),
          total_time_minutes INTEGER,
          time_cap_minutes INTEGER,
          has_buy_in BOOLEAN NOT NULL DEFAULT false,
          has_cash_out BOOLEAN NOT NULL DEFAULT false,
          is_complex BOOLEAN NOT NULL DEFAULT false,
          full_description TEXT,
          scraped_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
          source_page VARCHAR(100),
          status hyrox_status NOT NULL DEFAULT 'pending_review',
          notes TEXT
        )
        """,
        
        "CREATE INDEX idx_hyrox_workouts_staging_name ON hyrox_workouts_staging(name)",
        "CREATE INDEX idx_hyrox_workouts_staging_type ON hyrox_workouts_staging(workout_type)",
        "CREATE INDEX idx_hyrox_workouts_staging_status ON hyrox_workouts_staging(status)",
        "CREATE INDEX idx_hyrox_workouts_staging_scraped_at ON hyrox_workouts_staging(scraped_at)",
        
        """
        CREATE TABLE hyrox_mini_circuits_staging (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
          circuit_number INTEGER NOT NULL,
          circuit_type hyrox_workout_type NOT NULL,
          rounds INTEGER,
          start_time TIME,
          end_time TIME,
          duration_minutes INTEGER,
          rest_after_minutes INTEGER,
          notes TEXT,
          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """,
        "CREATE INDEX idx_hyrox_mini_circuits_staging_workout ON hyrox_mini_circuits_staging(workout_id)",
        
        """
        CREATE TABLE hyrox_time_segments_staging (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
          segment_number INTEGER NOT NULL,
          start_time TIME,
          end_time TIME,
          duration_minutes INTEGER,
          notes TEXT,
          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """,
        "CREATE INDEX idx_hyrox_time_segments_staging_workout ON hyrox_time_segments_staging(workout_id)",
        
        """
        CREATE TABLE hyrox_ladder_rungs_staging (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
          rung_number INTEGER NOT NULL,
          reps_per_exercise INTEGER,
          is_ascending BOOLEAN NOT NULL DEFAULT true,
          notes TEXT,
          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """,
        "CREATE INDEX idx_hyrox_ladder_rungs_staging_workout ON hyrox_ladder_rungs_staging(workout_id)",
        
        """
        CREATE TABLE hyrox_workout_lines_staging (
          id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          workout_id INTEGER NOT NULL REFERENCES hyrox_workouts_staging(id) ON DELETE CASCADE,
          line_number INTEGER NOT NULL,
          line_text TEXT NOT NULL,
          is_rest BOOLEAN NOT NULL DEFAULT false,
          is_buy_in BOOLEAN NOT NULL DEFAULT false,
          is_cash_out BOOLEAN NOT NULL DEFAULT false,
          movement_name VARCHAR(200),
          reps INTEGER,
          distance_meters NUMERIC(10,2),
          duration_seconds INTEGER,
          weight_male NUMERIC(10,2),
          weight_female NUMERIC(10,2),
          calories INTEGER,
          is_max_effort BOOLEAN NOT NULL DEFAULT false,
          notes TEXT,
          mini_circuit_id INTEGER REFERENCES hyrox_mini_circuits_staging(id) ON DELETE SET NULL,
          time_segment_id INTEGER REFERENCES hyrox_time_segments_staging(id) ON DELETE SET NULL,
          ladder_rung_id INTEGER REFERENCES hyrox_ladder_rungs_staging(id) ON DELETE SET NULL,
          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
        )
        """,
        "CREATE INDEX idx_hyrox_workout_lines_staging_workout ON hyrox_workout_lines_staging(workout_id)",
        "CREATE INDEX idx_hyrox_workout_lines_staging_movement ON hyrox_workout_lines_staging(movement_name)",
        "CREATE INDEX idx_hyrox_workout_lines_staging_circuit ON hyrox_workout_lines_staging(mini_circuit_id)",
        "CREATE INDEX idx_hyrox_workout_lines_staging_segment ON hyrox_workout_lines_staging(time_segment_id)",
        "CREATE INDEX idx_hyrox_workout_lines_staging_ladder ON hyrox_workout_lines_staging(ladder_rung_id)"
    ]
    
    try:
        for i, cmd in enumerate(commands):
            print(f"Executing command {i+1}...")
            cursor.execute(cmd)
            print(f"Command {i+1} executed.")
            
        print("All commands executed successfully.")
        
        # Verify
        cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_name = 'hyrox_workouts_staging'")
        res = cursor.fetchone()
        if res:
            print(f"Verification: Table {res[0]} exists!")
        else:
            print("Verification: Table hyrox_workouts_staging NOT FOUND!")
            
    except psycopg2.Error as e:
        print(f"PostgreSQL Error: {e}")
        print(f"Diagnostics: {e.diag.message_primary if e.diag else 'No diagnostics'}")
    except Exception as e:
        print(f"General Error: {e}")
    finally:
        cursor.close()
        conn.close()

if __name__ == "__main__":
    apply_migration_step_by_step()
